name: real-estate-analysis-torch
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - pillow
  - pytorch::pytorch
  - torchvision
  - torchaudio
  - lightning
  - torchinfo
  - tqdm
  - beautifulsoup4
  - matplotlib
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1